### PR TITLE
Add dropdown datetime picker

### PR DESCRIPTION
**Pull request by Edgar-Cordova**
This should be merged after "replace-date-picker" pull request

### CODE REVIEW

**Comment by nranas** [comment]
I pulled and tested this branch locally and it doesn't seem to handle the oh so despicable Daylight Savings Time. That is why I chose to use UTC times throughout the application so I think we might need to continue with that. Could you try to update this branch to continue using UTC? 

Let me know if you don't think it makes sense when handling time or if there's any other issues. Or if you simply want to discuss this further :)

**Comment by Edgar-Cordova** [comment]
Updated to use UTC calls

**Comment by nranas** [comment]
Looks good @Edgar-Cordova!
Just one thing.. Since we now have unit-tests on the date component it would be nice to add some tests on this component as well :)

**Comment by Edgar-Cordova** [comment]
I missed the last comment. I will update this PR with the tests.

**Pull request merged**
